server:
  port: ${PORT:0}
  servlet:
    contextPath: /api/v1/rest-fraudes

fixer:
  token:

spring:
  application:
    name: api-fraudes
  datasource:
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    showSql: true
    hibernate:
      dllAuto: create-drop
    databsePlatform: org.hibernate.dialect.H"Dialect

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring:application.instanceId:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka